/** Mutable fake data — everything works offline */
window.MOCK = {
  curator: { id: 1, name: "Диана Куратор", initials: "ДК" },
  courses: [
    { id: 0, title: "Все", short: "Все" },
    { id: 10, title: "Дизайн и живопись техники", short: "ДЖТ" },
    { id: 11, title: "Математика", short: "Математика" },
  ],
  curators: [
    { id: 1, name: "Диана Куратор", courseId: 10, isChief: false },
    { id: 2, name: "Айгерим", courseId: 11, isChief: false },
    { id: 3, name: "Главный куратор", courseId: null, isChief: true },
  ],
  pickerStudents: [
    { id: 11, name: "Томирис Досымхан", phone: "+7 778 215 35 57" },
    { id: 12, name: "Ибраһим Орысбаев", phone: "+7 778 603 89 20" },
    { id: 13, name: "Ерман Нұрлыбек", phone: "+7 775 161 20 51" },
    { id: 14, name: "Іңкәр Жақсылық", phone: "+7 777 595 80 03" },
    { id: 15, name: "динара исенбай", phone: "+7 778 294 84 81" },
    { id: 16, name: "Kausar Duisenbai", phone: "+7 701 179 56 58" },
    { id: 17, name: "Сабыржан Жарылқасын", phone: "+7 771 498 87 10" },
    { id: 21, name: "Аружан Бек", phone: "+7 707 111 22 33" },
    { id: 22, name: "Нұрлан Сат", phone: "+7 707 444 55 66" },
    { id: 23, name: "Меруерт Қали", phone: "+7 708 777 88 99" },
    { id: 24, name: "Данияр Ом", phone: "+7 701 000 11 22" },
    { id: 31, name: "Алина Тест", phone: "+7 777 000 00 01" },
    { id: 32, name: "Болат Тест", phone: "+7 777 000 00 02" },
  ],
  groups: [
    {
      id: 1,
      name: "Викингтер",
      courseId: 10,
      courseLabel: "ДЖТ • Диана",
      curatorId: 1,
      studentsCount: 7,
      students: [
        { id: 11, name: "Томирис Досымхан", phone: "+7 778 215 35 57", initials: "ТД", color: "#5B6EC2", rank: 1, medal: "gold", score: 95, progress: "48/77", lastSeen: "был 25.09.26", pointsToday: 12, rankChange: 1 },
        { id: 12, name: "Ибраһим Орысбаев", phone: "+7 778 603 89 20", initials: "ИО", color: "#25AB7C", rank: 2, medal: "silver", score: 90, progress: "48/77", lastSeen: "был 3 часа назад", pointsToday: 8, rankChange: 0 },
        { id: 13, name: "Ерман Нұрлыбек", phone: "+7 775 161 20 51", initials: "ЕН", color: "#F28C28", rank: 3, medal: "bronze", score: 90, progress: "56/77", lastSeen: "был 3 часа назад", pointsToday: 5, rankChange: -1 },
        { id: 14, name: "Іңкәр Жақсылық", phone: "+7 777 595 80 03", initials: "ІЖ", color: "#9BB8DA", rank: 4, medal: null, score: 89, progress: "44/77", lastSeen: "был 3 часа назад", pointsToday: 3, rankChange: 2 },
        { id: 15, name: "динара исенбай", phone: "+7 778 294 84 81", initials: "ДИ", color: "#CD7F32", rank: 5, medal: null, score: 78, progress: "20/77", lastSeen: "был 3 часа назад", pointsToday: 0, rankChange: 0 },
        { id: 16, name: "Kausar Duisenbai", phone: "+7 701 179 56 58", initials: "KD", color: "#85899A", rank: 6, medal: null, score: 75, progress: "52/77", lastSeen: "был 3 часа назад", pointsToday: 1, rankChange: -2 },
        { id: 17, name: "Сабыржан Жарылқасын", phone: "+7 771 498 87 10", initials: "СЖ", color: "#FF6767", rank: 7, medal: null, score: 0, progress: "8/77", lastSeen: "был 24.09.26", pointsToday: 0, rankChange: 0 },
      ],
    },
    {
      id: 2,
      name: "Nomad 11",
      courseId: 11,
      courseLabel: "Математика • Айгерим",
      curatorId: 2,
      studentsCount: 4,
      students: [
        { id: 21, name: "Аружан Бек", phone: "+7 707 111 22 33", initials: "АБ", color: "#5B6EC2", rank: 1, medal: "gold", score: 88, progress: "30/50", lastSeen: "онлайн", pointsToday: 10, rankChange: 0 },
        { id: 22, name: "Нұрлан Сат", phone: "+7 707 444 55 66", initials: "НС", color: "#25AB7C", rank: 2, medal: "silver", score: 71, progress: "22/50", lastSeen: "был час назад", pointsToday: 4, rankChange: 1 },
        { id: 23, name: "Меруерт Қали", phone: "+7 708 777 88 99", initials: "МҚ", color: "#F28C28", rank: 3, medal: "bronze", score: 54, progress: "15/50", lastSeen: "был вчера", pointsToday: 0, rankChange: -1 },
        { id: 24, name: "Данияр Ом", phone: "+7 701 000 11 22", initials: "ДО", color: "#85899A", rank: 4, medal: null, score: 12, progress: "3/50", lastSeen: "был 20.09.26", pointsToday: 0, rankChange: 0 },
      ],
    },
    {
      id: 3,
      name: "Старт А",
      courseId: 0,
      courseLabel: "Все • Главный куратор",
      curatorId: 3,
      studentsCount: 2,
      students: [
        { id: 31, name: "Алина Тест", phone: "+7 777 000 00 01", initials: "АТ", color: "#9BB8DA", rank: 1, medal: "gold", score: 40, progress: "10/40", lastSeen: "был 2 часа назад", pointsToday: 2, rankChange: 0 },
        { id: 32, name: "Болат Тест", phone: "+7 777 000 00 02", initials: "БТ", color: "#CD7F32", rank: 2, medal: "silver", score: 18, progress: "4/40", lastSeen: "был 5 часов назад", pointsToday: 0, rankChange: 0 },
      ],
    },
  ],
  students: [
    { id: 11, name: "Томирис Досымхан", phone: "+7 778 215 35 57", initials: "ТД", color: "#5B6EC2", status: "online", course: "ДЖТ", progress: "48/77", blocked: false },
    { id: 12, name: "Ибраһим Орысбаев", phone: "+7 778 603 89 20", initials: "ИО", color: "#25AB7C", status: "recent", course: "ДЖТ", progress: "48/77", blocked: false },
    { id: 21, name: "Аружан Бек", phone: "+7 707 111 22 33", initials: "АБ", color: "#5B6EC2", status: "online", course: "Математика", progress: "30/50", blocked: false },
    { id: 22, name: "Нұрлан Сат", phone: "+7 707 444 55 66", initials: "НС", color: "#25AB7C", status: "recent", course: "Математика", progress: "22/50", blocked: false },
    { id: 31, name: "Алина Тест", phone: "+7 777 000 00 01", initials: "АТ", color: "#9BB8DA", status: "offline", course: "Все", progress: "10/40", blocked: true },
  ],
  enrollments: [
    { id: 101, student: "Томирис Досымхан", phone: "+7 778 215 35 57", course: "ДЖТ", courseId: 10, status: "active", statusLabel: "Активен", date: "01.09.2026", daysLeft: 62 },
    { id: 102, student: "Аружан Бек", phone: "+7 707 111 22 33", course: "Математика", courseId: 11, status: "active", statusLabel: "Активен", date: "10.09.2026", daysLeft: 80 },
    { id: 103, student: "Нұрлан Сат", phone: "+7 707 444 55 66", course: "Математика", courseId: 11, status: "freeze", statusLabel: "Заморозка", date: "05.08.2026", daysLeft: null },
    { id: 104, student: "Данияр Ом", phone: "+7 701 000 11 22", course: "ДЖТ", courseId: 10, status: "pending", statusLabel: "Ожидает", date: "27.09.2026", daysLeft: 90 },
  ],
  pushes: [
    { id: 1, title: "Напоминание: конспект", body: "Ребята, сдайте конспекты за эту неделю до пятницы.", time: "сегодня, 10:24", audience: "Викингтер" },
    { id: 2, title: "Эфир в 19:00", body: "Разбор сложных задач. Ссылка уже в группе.", time: "вчера, 18:02", audience: "Все кураторские" },
    { id: 3, title: "Поздравляем топ‑3!", body: "Томирис, Ибраһим и Ерман — лучшие за неделю", time: "25.09.2026", audience: "Викингтер" },
  ],
  efirs: [
    { id: 1, title: "Разбор ДЖТ", when: "сегодня 19:00", status: "planned" },
    { id: 2, title: "Математика: модуль 3", when: "вчера 18:00", status: "done" },
  ],
  pushTypes: [
    { value: "announcement", label: "Объявление" },
    { value: "reminder", label: "Напоминание" },
    { value: "urgent", label: "Срочно" },
  ],
  audiences: [
    { value: "all", label: "Все" },
    { value: "group", label: "Группа" },
    { value: "course", label: "Курс" },
    { value: "student", label: "Ученик" },
  ],
  filters: {
    studentBlocked: null,
    enrollmentStatus: null,
  },
  /** Logged-in user (profile screen) */
  me: {
    firstName: "Томирис",
    lastName: "Досымхан",
    initials: "ТД",
    color: "#5B6EC2",
    phone: "+7 778 215 35 57",
    canStaff: true,
  },
  stories: [
    { id: 1, title: "Старт недели", hue: "linear-gradient(135deg,#3d4a8c,#1e2744 55%,#6b4a2a)" },
    { id: 2, title: "Эфир", hue: "linear-gradient(135deg,#2a6b55,#1a3d38)" },
    { id: 3, title: "ДЖТ", hue: "linear-gradient(135deg,#5b3d8c,#2b1d44)" },
  ],
  myCourses: [
    {
      id: 10,
      title: "Ағылшын тілі",
      total: 48,
      done: 12,
      days: 74,
      progress: 12 / 48,
      color: "#1E3A8A",
      thumb: "assets/v2/eng_uk.png",
    },
    {
      id: 11,
      title: "Дүниежүзі тарихы",
      total: 36,
      done: 9,
      days: 74,
      progress: 9 / 36,
      color: "#4F6D7A",
      thumb: "assets/v2/history_world.png",
    },
  ],
  scheduleToday: [
    {
      id: 1,
      course: "Ағылшын Тілі",
      lesson: "Prepositions",
      icon: "play_arrow",
      accent: "#4FB1BA",
      done: true,
    },
    {
      id: 2,
      course: "Дүниежүзі Тарихы",
      lesson: "Осман империясы (1)",
      icon: "replay",
      accent: "#5CB36D",
      done: false,
    },
  ],
  news: [
    { id: 1, title: "Бір платформа — барлық пәндер", body: "Барлық пәндер бір қосымшада. Эфирлер, тесттер және тренажёр.", thumb: "assets/v2/news.png" },
    { id: 2, title: "Пробный ЕНТ открыт", body: "Выберите комбинацию предметов и начните пробный тест.", thumb: "assets/v2/testv2.png" },
    { id: 3, title: "Справочник профессий", body: "Специальности и вузы Казахстана в одном списке.", thumb: "assets/v2/profv2.png" },
  ],
  studentNotifs: [
    { id: 1, when: "Сегодня 10:24", title: "Вас зачислили в курс", body: "Теперь у вас есть полный доступ к курсу. Удачи в обучении!" },
    { id: 2, when: "Вчера 18:02", title: "Эфир в 19:00", body: "Разбор Prepositions. Ссылка уже в курсе." },
    { id: 3, when: "25 сентября 12:10", title: "Напоминание: конспект", body: "Сдайте конспект по теме Prepositions до пятницы." },
  ],
  subjects: [
    { title: "Математика", color: "#4690C6", img: "assets/v2/math.png" },
    { title: "Физика", color: "#5853C7", img: "assets/v2/physics.png" },
    { title: "Химия", color: "#8F2EA8", img: "assets/v2/chemistry.png" },
    { title: "Биология", color: "#2D8B48", img: "assets/v2/bio.png" },
    { title: "Ағылшын тілі", color: "#1E3A8A", img: "assets/v2/eng_uk.png" },
    { title: "Дүниежүзі тарихы", color: "#4F6D7A", img: "assets/v2/history_world.png" },
    { title: "Қазақстан тарихы", color: "#2B8073", img: "assets/v2/history_kz_berkut.png" },
    { title: "География", color: "#13A4C8", img: "assets/v2/geo.png" },
    { title: "Информатика", color: "#B13B5D", img: "assets/v2/informatics.png" },
    { title: "Қазақ тілі", color: "#3B7BBF", img: "assets/v2/kaz_lang.png" },
  ],
  specialities: [
    { code: "B057", name: "Информационные технологии", meta: "Математика · Физика" },
    { code: "B044", name: "Менеджмент и управление", meta: "География · Математика" },
    { code: "B084", name: "Сестринское дело", meta: "Биология · Химия" },
    { code: "B050", name: "Биологические науки", meta: "Биология · Химия" },
  ],
  universities: [
    { code: "КазНУ", name: "Казахский национальный университет", city: "Алматы", kind: "гос." },
    { code: "ЕНУ", name: "Евразийский национальный университет", city: "Астана", kind: "гос." },
    { code: "Satbayev", name: "Satbayev University", city: "Алматы", kind: "гос." },
    { code: "KBTU", name: "Казахстанско-Британский технический университет", city: "Алматы", kind: "част." },
  ],
  trainerSubjects: [
    { title: "Ағылшын тілі", thumb: "assets/v2/eng_uk.png", percent: 28, done: 4, total: 14 },
    { title: "Дүниежүзі тарихы", thumb: "assets/v2/history_world.png", percent: 12, done: 2, total: 16 },
  ],
  _nextId: 1000,
};
