/** Mutable fake data — everything works offline */
window.MOCK = {
  curator: { id: 1, name: "Диана Куратор", initials: "ДК" },
  courses: [
    { id: 0, title: "Все", short: "Все" },
    { id: 10, title: "Дизайн и живопись техники", short: "ДЖТ" },
    { id: 11, title: "Математика", short: "Математика" },
  ],
  curators: [
    { id: 1, name: "Диана Куратор", courseId: 10, isChief: false },
    { id: 2, name: "Айгерим", courseId: 11, isChief: false },
    { id: 3, name: "Главный куратор", courseId: null, isChief: true },
  ],
  pickerStudents: [
    { id: 11, name: "Томирис Досымхан", phone: "+7 778 215 35 57" },
    { id: 12, name: "Ибраһим Орысбаев", phone: "+7 778 603 89 20" },
    { id: 13, name: "Ерман Нұрлыбек", phone: "+7 775 161 20 51" },
    { id: 14, name: "Іңкәр Жақсылық", phone: "+7 777 595 80 03" },
    { id: 15, name: "динара исенбай", phone: "+7 778 294 84 81" },
    { id: 16, name: "Kausar Duisenbai", phone: "+7 701 179 56 58" },
    { id: 17, name: "Сабыржан Жарылқасын", phone: "+7 771 498 87 10" },
    { id: 21, name: "Аружан Бек", phone: "+7 707 111 22 33" },
    { id: 22, name: "Нұрлан Сат", phone: "+7 707 444 55 66" },
    { id: 23, name: "Меруерт Қали", phone: "+7 708 777 88 99" },
    { id: 24, name: "Данияр Ом", phone: "+7 701 000 11 22" },
    { id: 31, name: "Алина Тест", phone: "+7 777 000 00 01" },
    { id: 32, name: "Болат Тест", phone: "+7 777 000 00 02" },
  ],
  groups: [
    {
      id: 1,
      name: "Викингтер",
      courseId: 10,
      courseLabel: "ДЖТ • Диана",
      curatorId: 1,
      studentsCount: 7,
      students: [
        { id: 11, name: "Томирис Досымхан", phone: "+7 778 215 35 57", initials: "ТД", color: "#5B6EC2", rank: 1, medal: "gold", score: 95, progress: "48/77", lastSeen: "был 25.09.26", pointsToday: 12, rankChange: 1 },
        { id: 12, name: "Ибраһим Орысбаев", phone: "+7 778 603 89 20", initials: "ИО", color: "#25AB7C", rank: 2, medal: "silver", score: 90, progress: "48/77", lastSeen: "был 3 часа назад", pointsToday: 8, rankChange: 0 },
        { id: 13, name: "Ерман Нұрлыбек", phone: "+7 775 161 20 51", initials: "ЕН", color: "#F28C28", rank: 3, medal: "bronze", score: 90, progress: "56/77", lastSeen: "был 3 часа назад", pointsToday: 5, rankChange: -1 },
        { id: 14, name: "Іңкәр Жақсылық", phone: "+7 777 595 80 03", initials: "ІЖ", color: "#9BB8DA", rank: 4, medal: null, score: 89, progress: "44/77", lastSeen: "был 3 часа назад", pointsToday: 3, rankChange: 2 },
        { id: 15, name: "динара исенбай", phone: "+7 778 294 84 81", initials: "ДИ", color: "#CD7F32", rank: 5, medal: null, score: 78, progress: "20/77", lastSeen: "был 3 часа назад", pointsToday: 0, rankChange: 0 },
        { id: 16, name: "Kausar Duisenbai", phone: "+7 701 179 56 58", initials: "KD", color: "#85899A", rank: 6, medal: null, score: 75, progress: "52/77", lastSeen: "был 3 часа назад", pointsToday: 1, rankChange: -2 },
        { id: 17, name: "Сабыржан Жарылқасын", phone: "+7 771 498 87 10", initials: "СЖ", color: "#FF6767", rank: 7, medal: null, score: 0, progress: "8/77", lastSeen: "был 24.09.26", pointsToday: 0, rankChange: 0 },
      ],
    },
    {
      id: 2,
      name: "Nomad 11",
      courseId: 11,
      courseLabel: "Математика • Айгерим",
      curatorId: 2,
      studentsCount: 4,
      students: [
        { id: 21, name: "Аружан Бек", phone: "+7 707 111 22 33", initials: "АБ", color: "#5B6EC2", rank: 1, medal: "gold", score: 88, progress: "30/50", lastSeen: "онлайн", pointsToday: 10, rankChange: 0 },
        { id: 22, name: "Нұрлан Сат", phone: "+7 707 444 55 66", initials: "НС", color: "#25AB7C", rank: 2, medal: "silver", score: 71, progress: "22/50", lastSeen: "был час назад", pointsToday: 4, rankChange: 1 },
        { id: 23, name: "Меруерт Қали", phone: "+7 708 777 88 99", initials: "МҚ", color: "#F28C28", rank: 3, medal: "bronze", score: 54, progress: "15/50", lastSeen: "был вчера", pointsToday: 0, rankChange: -1 },
        { id: 24, name: "Данияр Ом", phone: "+7 701 000 11 22", initials: "ДО", color: "#85899A", rank: 4, medal: null, score: 12, progress: "3/50", lastSeen: "был 20.09.26", pointsToday: 0, rankChange: 0 },
      ],
    },
    {
      id: 3,
      name: "Старт А",
      courseId: 0,
      courseLabel: "Все • Главный куратор",
      curatorId: 3,
      studentsCount: 2,
      students: [
        { id: 31, name: "Алина Тест", phone: "+7 777 000 00 01", initials: "АТ", color: "#9BB8DA", rank: 1, medal: "gold", score: 40, progress: "10/40", lastSeen: "был 2 часа назад", pointsToday: 2, rankChange: 0 },
        { id: 32, name: "Болат Тест", phone: "+7 777 000 00 02", initials: "БТ", color: "#CD7F32", rank: 2, medal: "silver", score: 18, progress: "4/40", lastSeen: "был 5 часов назад", pointsToday: 0, rankChange: 0 },
      ],
    },
  ],
  students: [
    { id: 11, name: "Томирис Досымхан", phone: "+7 778 215 35 57", initials: "ТД", color: "#5B6EC2", status: "online", course: "ДЖТ", progress: "48/77", blocked: false },
    { id: 12, name: "Ибраһим Орысбаев", phone: "+7 778 603 89 20", initials: "ИО", color: "#25AB7C", status: "recent", course: "ДЖТ", progress: "48/77", blocked: false },
    { id: 21, name: "Аружан Бек", phone: "+7 707 111 22 33", initials: "АБ", color: "#5B6EC2", status: "online", course: "Математика", progress: "30/50", blocked: false },
    { id: 22, name: "Нұрлан Сат", phone: "+7 707 444 55 66", initials: "НС", color: "#25AB7C", status: "recent", course: "Математика", progress: "22/50", blocked: false },
    { id: 31, name: "Алина Тест", phone: "+7 777 000 00 01", initials: "АТ", color: "#9BB8DA", status: "offline", course: "Все", progress: "10/40", blocked: true },
  ],
  enrollments: [
    { id: 101, student: "Томирис Досымхан", phone: "+7 778 215 35 57", course: "ДЖТ", courseId: 10, status: "active", statusLabel: "Активен", date: "01.09.2026", daysLeft: 62 },
    { id: 102, student: "Аружан Бек", phone: "+7 707 111 22 33", course: "Математика", courseId: 11, status: "active", statusLabel: "Активен", date: "10.09.2026", daysLeft: 80 },
    { id: 103, student: "Нұрлан Сат", phone: "+7 707 444 55 66", course: "Математика", courseId: 11, status: "freeze", statusLabel: "Заморозка", date: "05.08.2026", daysLeft: null },
    { id: 104, student: "Данияр Ом", phone: "+7 701 000 11 22", course: "ДЖТ", courseId: 10, status: "pending", statusLabel: "Ожидает", date: "27.09.2026", daysLeft: 90 },
  ],
  pushes: [
    { id: 1, title: "Напоминание: конспект", body: "Ребята, сдайте конспекты за эту неделю до пятницы.", time: "сегодня, 10:24", audience: "Викингтер" },
    { id: 2, title: "Эфир в 19:00", body: "Разбор сложных задач. Ссылка уже в группе.", time: "вчера, 18:02", audience: "Все кураторские" },
    { id: 3, title: "Поздравляем топ‑3!", body: "Томирис, Ибраһим и Ерман — лучшие за неделю", time: "25.09.2026", audience: "Викингтер" },
  ],
  efirs: [
    { id: 1, title: "Разбор ДЖТ", when: "сегодня 19:00", status: "planned" },
    { id: 2, title: "Математика: модуль 3", when: "вчера 18:00", status: "done" },
  ],
  pushTypes: [
    { value: "announcement", label: "Объявление" },
    { value: "reminder", label: "Напоминание" },
    { value: "urgent", label: "Срочно" },
  ],
  audiences: [
    { value: "all", label: "Все" },
    { value: "group", label: "Группа" },
    { value: "course", label: "Курс" },
    { value: "student", label: "Ученик" },
  ],
  filters: {
    studentBlocked: null,
    enrollmentStatus: null,
  },
  /** Logged-in user (profile screen) */
  me: {
    firstName: "Томирис",
    lastName: "Досымхан",
    initials: "ТД",
    color: "#5B6EC2",
    phone: "+7 778 215 35 57",
    canStaff: true,
  },
  stories: [
    { id: 1, title: "Старт недели", hue: "linear-gradient(135deg,#3d4a8c,#1e2744 55%,#6b4a2a)" },
    { id: 2, title: "Эфир", hue: "linear-gradient(135deg,#2a6b55,#1a3d38)" },
    { id: 3, title: "ДЖТ", hue: "linear-gradient(135deg,#5b3d8c,#2b1d44)" },
  ],
  myCourses: [
    {
      id: 10,
      title: "Ағылшын тілі",
      total: 128,
      done: 0,
      days: 334,
      poster: { lines: ["АҒЫЛШЫН", "ТІЛІ"], bg: "linear-gradient(135deg,#7b2fc0,#5a1f9a)", img: "assets/v2/eng_uk.png" },
    },
    {
      id: 11,
      title: "Дүниежүзі Тарихы",
      total: 172,
      done: 0,
      days: 334,
      poster: { lines: ["ДҮНИЕЖҮЗІ", "ТАРИХЫ"], bg: "linear-gradient(135deg,#3f8a78,#2e6e5f)", img: "assets/v2/history_world.png" },
    },
  ],
  /** «Расписание»: kind → video | test; when → today | overdue | дата */
  schedule: {
    stats: { today: 2, week: 16, overdue: 61 },
    day: "02.10",
    week: "28.09 – 04.10",
    month: "Октябрь",
    items: [
      { id: 1, course: "Ағылшын тілі", lesson: "Prepositions", kind: "video", week: 4, when: "today", period: ["day", "week", "month"] },
      { id: 2, course: "Дүниежүзі Тарихы", lesson: "Осман империясы (1)", kind: "test", week: 4, when: "today", period: ["day", "week", "month"] },
      { id: 3, course: "Ағылшын тілі", lesson: "Articles: a / an / the", kind: "video", week: 4, when: "03.10", period: ["week", "month"] },
      { id: 4, course: "Дүниежүзі Тарихы", lesson: "Ұлы географиялық ашулар", kind: "video", week: 4, when: "04.10", period: ["week", "month"] },
      { id: 5, course: "Ағылшын тілі", lesson: "Present Simple", kind: "test", week: 3, when: "overdue", period: ["week", "month"] },
      { id: 6, course: "Дүниежүзі Тарихы", lesson: "Қайта өрлеу дәуірі", kind: "video", week: 5, when: "09.10", period: ["month"] },
    ],
  },
  scheduleToday: [
    { id: 1, course: "Ағылшын тілі", lesson: "Prepositions", kind: "video" },
    { id: 2, course: "Дүниежүзі Тарихы", lesson: "Осман империясы (1)", kind: "test" },
  ],
  news: [
    { id: 1, title: "Қазақстанның үздік университеттері:", body: "Қазақстанның ең беделді университеттерінің тізімін ұсынамыз. Грант, жатақхана және мамандықтар туралы.", thumb: { kind: "unis" } },
    { id: 2, title: "🎓 ЕҢ КӨП ГРАНТ БӨЛІНГЕН МАМАНДЫҚТАР", body: "Грант саны көп бөлінген мамандықтар – болашақта сұранысқа ие кәсіптер тізімі.", thumb: { kind: "grants" } },
    { id: 3, title: "I4U платформасы саған қалай көмектесе алады?", body: "🚀 Дайын бейне курстар – Қанша ұпай жинағаныңды бақылап, әлсіз тақырыптарды жаба аласың.", thumb: { kind: "app" } },
    { id: 4, title: "Қазақстанның үздік университеттері:", body: "Қазақстанның ең беделді университеттерінің тізімін ұсынамыз. Грант, жатақхана және мамандықтар туралы.", thumb: null },
    { id: 5, title: "ҰБТ-ға пайдалы және керек материалдар", body: "ҰБТ пәндері бойынша барлық маңызды материалдарды тегін жинап, бір жерге қойдық.", thumb: null },
  ],
  studentNotifs: [
    { id: 1, when: "Сегодня 10:24", title: "Вас зачислили в курс", body: "Теперь у вас есть полный доступ к курсу. Удачи в обучении!" },
    { id: 2, when: "Вчера 18:02", title: "Эфир в 19:00", body: "Разбор Prepositions. Ссылка уже в курсе." },
    { id: 3, when: "25 сентября 12:10", title: "Напоминание: конспект", body: "Сдайте конспект по теме Prepositions до пятницы." },
  ],
  subjects: [
    { title: "Математика", color: "#4690C6", img: "assets/v2/math.png" },
    { title: "Физика", color: "#5853C7", img: "assets/v2/physics.png" },
    { title: "Химия", color: "#8F2EA8", img: "assets/v2/chemistry.png" },
    { title: "Биология", color: "#2D8B48", img: "assets/v2/bio.png" },
    { title: "Ағылшын тілі", color: "#1E3A8A", img: "assets/v2/eng_uk.png" },
    { title: "Дүниежүзі тарихы", color: "#4F6D7A", img: "assets/v2/history_world.png" },
    { title: "Қазақстан тарихы", color: "#2B8073", img: "assets/v2/history_kz_berkut.png" },
    { title: "География", color: "#13A4C8", img: "assets/v2/geo.png" },
    { title: "Информатика", color: "#B13B5D", img: "assets/v2/informatics.png" },
    { title: "Қазақ тілі", color: "#3B7BBF", img: "assets/v2/kaz_lang.png" },
  ],
  /** Профессии → Специальности (код, атауы, бейіндік пәндер) */
  specialities: [
    { code: "B001", name: "Педагогика және психология", subjects: "Биология – География" },
    { code: "B002", name: "Мектепке дейінгі оқыту және тәрбиелеу", subjects: "Биология – География" },
    { code: "B003", name: "Бастауышта оқыту педагогикасы мен әдістемесі", subjects: "Биология – География" },
    { code: "B004", name: "Бастапқы әскери дайындық мұғалімдерін даярлау", subjects: "Шығармашылық" },
    { code: "B005", name: "Дене шынықтыру мұғалімдерін даярлау", subjects: "Шығармашылық" },
    { code: "B006", name: "Музыка мұғалімдерін даярлау", subjects: "Шығармашылық" },
    { code: "B007", name: "Көркем еңбек және сызу мұғалімдерін даярлау", subjects: "Шығармашылық" },
    { code: "B008", name: "Құқық және экономика негіздері мұғалімдерін даярлау", subjects: "Дүниежүзі тарихы – Құқық негіздері" },
    { code: "B009", name: "Математика мұғалімдерін даярлау", subjects: "Математика – Физика" },
    { code: "B010", name: "Физика мұғалімдерін даярлау", subjects: "Математика – Физика" },
    { code: "B011", name: "Информатика мұғалімдерін даярлау", subjects: "Математика – Информатика" },
    { code: "B012", name: "Химия мұғалімдерін даярлау", subjects: "Химия – Биология" },
    { code: "B013", name: "Биология мұғалімдерін даярлау", subjects: "Биология – Химия" },
    { code: "B014", name: "География мұғалімдерін даярлау", subjects: "География – Дүниежүзі тарихы" },
    { code: "B016", name: "Қазақ тілі мен әдебиеті мұғалімдерін даярлау", subjects: "Қазақ тілі – Қазақ әдебиеті" },
    { code: "B018", name: "Шет тілі мұғалімдерін даярлау", subjects: "Шет тілі – Дүниежүзі тарихы" },
    { code: "B044", name: "Менеджмент және басқару", subjects: "Математика – География" },
    { code: "B046", name: "Қаржы, экономика, банк және сақтандыру ісі", subjects: "Математика – География" },
    { code: "B049", name: "Құқық", subjects: "Дүниежүзі тарихы – Құқық негіздері" },
    { code: "B050", name: "Биологиялық және сабақтас ғылымдар", subjects: "Биология – Химия" },
    { code: "B057", name: "Ақпараттық технологиялар", subjects: "Математика – Информатика" },
    { code: "B058", name: "Ақпараттық қауіпсіздік", subjects: "Математика – Информатика" },
    { code: "B062", name: "Электр техникасы және энергетика", subjects: "Математика – Физика" },
    { code: "B086", name: "Жалпы медицина", subjects: "Биология – Химия" },
  ],
  /** Профессии → ВУЗы. logo: null → бас әріптер */
  universities: [
    { code: "013", name: "Л. Н. Гумилев атындағы Еуразия ұлттық университеті", short: "ЕҰУ", city: "Астана қ.", gov: true },
    { code: "002", name: "Қазақ ұлттық өнер университеті", short: "ҚҰ", city: "Астана қ.", gov: true },
    { code: "003", name: "Қазақ ұлттық хореография академиясы", short: "ҚҰ", city: "Астана қ.", gov: true },
    { code: "004", name: "С. Сейфуллин атындағы Қазақ агротехникалық университеті", short: "SU", city: "Астана қ.", gov: false },
    { code: "005", name: "Астана медицина университеті", short: "АМ", city: "Астана қ.", gov: false },
    { code: "010", name: "Әл-Фараби атындағы Қазақ ұлттық университеті", short: "ҚҰ", city: "Алматы қ.", gov: true },
    { code: "007", name: "Abai University", short: "AU", city: "Алматы қ.", gov: true },
    { code: "025", name: "Қазақ ұлттық қыздар педагогикалық университеті", short: "ҚҚ", city: "Алматы қ.", gov: true },
    { code: "029", name: "Satbayev University", short: "SU", city: "Алматы қ.", gov: false },
    { code: "041", name: "Қазақстан-Британ техникалық университеті", short: "KB", city: "Алматы қ.", gov: false },
    { code: "045", name: "SDU University", short: "SD", city: "Алматы обл.", gov: false },
    { code: "031", name: "Karaganda Buketov University", short: "KB", city: "Қарағанды обл.", gov: true },
    { code: "034", name: "Zhubanov University", short: "ZU", city: "Ақтөбе обл.", gov: true },
    { code: "008", name: "Altynsarin University (Арқалық педагогикалық институты)", short: "AU", city: "Қостанай обл.", gov: true },
    { code: "052", name: "М. Әуезов атындағы Оңтүстік Қазақстан университеті", short: "ОҚ", city: "Түркістан обл.", gov: true },
  ],
  trainerSubjects: [
    {
      id: 10,
      title: "Ағылшын тілі",
      courseId: 10,
      percent: 0,
      done: 0,
      total: 47,
      weak: 0,
      closed: 0,
      sections: [
        {
          title: "Nouns, Pronouns & Basic Tenses",
          percent: 0,
          topics: ["Countable / uncountable nouns", "Personal pronouns", "Possessive pronouns", "Present Simple", "Present Continuous", "Past Simple", "Future Simple"],
          count: 47,
        },
      ],
    },
    {
      id: 11,
      title: "Дүниежүзі Тарихы",
      courseId: 11,
      percent: 1,
      done: 0,
      total: 52,
      weak: 1,
      closed: 0,
      sections: [
        { title: "Ежелгі дүние тарихы", percent: 2, topics: ["Ежелгі Египет", "Ежелгі Греция", "Ежелгі Рим"], count: 18 },
        { title: "Орта ғасырлар", percent: 0, topics: ["Византия", "Араб халифаты", "Осман империясы"], count: 20 },
        { title: "Жаңа заман", percent: 0, topics: ["Ұлы географиялық ашулар", "Қайта өрлеу дәуірі"], count: 14 },
      ],
    },
  ],
  /** Тренажёр → Умная практика: сұрақтар (answer = дұрыс жауап индексі) */
  practice: {
    10: {
      topic: "Phrasal Verbs",
      questions: [
        { q: "Choose the word opposite in meaning: enter.", options: ["Sing.", "Jump.", "Play.", "Leave."], answer: 3 },
        { q: "Choose the correct phrasal verb: Please ___ the lights when you leave.", options: ["turn off", "turn up", "take off", "put up"], answer: 0 },
        { q: "“To give up” means…", options: ["to start", "to stop doing something", "to return", "to wait"], answer: 1 },
        { q: "She ___ her grandmother every Sunday.", options: ["looks after", "looks for", "looks up", "looks like"], answer: 0 },
        { q: "Choose the synonym of “find out”.", options: ["forget", "discover", "hide", "lose"], answer: 1 },
      ],
    },
    11: {
      topic: "Осман империясы",
      questions: [
        { q: "Осман империясының негізін қалаған кім?", options: ["Осман I", "Мехмед II", "Сүлейман I", "Селим I"], answer: 0 },
        { q: "Константинополь қай жылы бағындырылды?", options: ["1299", "1453", "1529", "1683"], answer: 1 },
        { q: "«Заң шығарушы» атанған сұлтан:", options: ["Баязид I", "Мұрат II", "Сүлейман I", "Ахмед I"], answer: 2 },
        { q: "Осман армиясының жаяу әскері қалай аталды?", options: ["Сипахилер", "Янычарлар", "Мамлюктер", "Казактар"], answer: 1 },
        { q: "Осман империясы ресми түрде қай жылы жойылды?", options: ["1908", "1918", "1922", "1945"], answer: 2 },
      ],
    },
  },
  /** Аналитика */
  analytics: {
    goal: null,
    courses: { done: 2, total: 5 },
    lessons: { done: 0, total: 0 },
    tests: { done: 0, total: 200 },
    mockTests: 2,
  },
  /** Тесты → ЕНТ: выбор комбинации */
  entPicker: {
    electives: [
      { id: "math", title: "Математика", color: "#5B8FD6" },
      { id: "phys", title: "Физика", color: "#7B76E0" },
      { id: "inf", title: "Информатика", color: "#D0607F" },
      { id: "geo", title: "География", color: "#4FB1BA" },
      { id: "bio", title: "Биология", color: "#5CB36D" },
      { id: "chem", title: "Химия", color: "#B05CC8" },
      { id: "djt", title: "ДЖТ", color: "#E0A040" },
      { id: "eng", title: "Английский", color: "#5B6EC2" },
      { id: "law", title: "Право", color: "#C98A5A" },
      { id: "kz", title: "Қазақ тілі", color: "#3B9BD6" },
      { id: "kzlit", title: "Қазақ әдебиеті", color: "#D6834F" },
    ],
    core: [
      { title: "История", color: "#4FA78A" },
      { title: "Математическая грамотность", color: "#5B8FD6" },
    ],
    selected: ["math", "geo"],
  },
  _nextId: 1000,
};
